title: Mobile American Notary & Apostilles
url: "https://www.mobileamericannotary.com"
baseurl: ""
description: "Expert mobile notary and apostille services in Los Angeles"

permalink: /blog/:title/

markdown: kramdown

plugins:
  - jekyll-feed

include:
  - "*.html"
  - "*.shtml"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - order-form/Spread Sheets & Scripts
  - "*.py"
  - fix-ga-tags.sh
  - vendor

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"

